version: 2
jobs:
  build:
    docker:
      - image: node:11.10.1
    working_directory: ~/my-app
    branches:
      only:
        - master
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: npm run netlify:deploy
