version: 2
jobs:
  build:
    docker:
      - image: node:11.10.1
    working_directory: ~/my-repos
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Netlify CLI Setup
          command: |
            npm install netlify-cli -g
      - run:
          command: |
            cd my-app
            npm install
            npm run test
            npm run build
            echo $NETLIFY_SITE_ID
            echo $NETLIFY_ACCESS_TOKEN
            netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod
